# ============================================================
# Hiver SDE Intern Assignment
# Step 3 - Brand Issue / Text Diversity Analysis
# ============================================================
#
# PURPOSE:
# We have already identified the top support/brand accounts
# based on customer interaction volume.
#
# In this step, we examine the actual customer messages
# associated with those brands.
#
# The goal is NOT to create the final intent taxonomy yet.
# Instead, we want to determine whether a brand has enough
# variation in customer issues to support approximately
# 8-12 meaningful intents.
#
# ============================================================


# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

# Path provides safe Windows/Linux file paths.
from pathlib import Path

# pandas is used for reading and analyzing the CSV dataset.
import pandas as pd

# re is used for simple text cleaning and tokenization.
import re


# ============================================================
# 2. DEFINE PROJECT PATHS
# ============================================================

# __file__ is the path of this Python script:
#
# hiver-sde-agent/src/03_brand_issue_analysis.py
#
# .parent       -> hiver-sde-agent/src
# .parent.parent -> hiver-sde-agent
#
# Therefore PROJECT_ROOT points to our main project folder.
PROJECT_ROOT = Path(__file__).resolve().parent.parent


# Original 516 MB Customer Support on Twitter dataset.
DATA_PATH = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "twcs.csv"
)


# Output from our previous conversation-level analysis.
BRAND_ANALYSIS_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "brand_conversation_analysis.csv"
)


# Where this script will save its results.
OUTPUT_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "brand_issue_analysis.csv"
)


# Create the output folder if it does not already exist.
OUTPUT_PATH.parent.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# 3. SETTINGS
# ============================================================

# We will examine the top 10 brands from our previous
# conversation-level analysis.
#
# This keeps the analysis manageable while still giving us
# several strong candidates to compare.
TOP_N = 10


# The dataset is about 516 MB.
# Reading 100,000 rows at a time avoids loading the entire
# dataset into memory.
CHUNK_SIZE = 100_000


# Maximum number of customer messages that we will retain
# per brand for this exploratory analysis.
#
# This is NOT our final evaluation sample.
MAX_MESSAGES_PER_BRAND = 20_000


# ============================================================
# 4. CHECK REQUIRED FILES
# ============================================================

# Make sure the raw Twitter dataset exists.
if not DATA_PATH.exists():
    raise FileNotFoundError(
        f"\nDataset not found:\n{DATA_PATH}\n\n"
        "Make sure twcs.csv is inside data/raw/"
    )


# Make sure the previous brand conversation analysis exists.
if not BRAND_ANALYSIS_PATH.exists():
    raise FileNotFoundError(
        f"\nPrevious analysis file not found:\n"
        f"{BRAND_ANALYSIS_PATH}\n\n"
        "Run 02_brand_conversation_analysis.py first."
    )


# ============================================================
# 5. LOAD TOP BRAND CANDIDATES
# ============================================================

# Read the CSV generated by Script 02.
brands_df = pd.read_csv(
    BRAND_ANALYSIS_PATH
)


# Sort brands by the number of direct customer interactions.
brands_df = (
    brands_df
    .sort_values(
        "direct_customer_interactions",
        ascending=False
    )
    .head(TOP_N)
    .copy()
)


# Convert brand names into a Python set for fast filtering.
candidate_brands = set(
    brands_df["author_id"]
    .astype(str)
)


# Display the candidates.
print("=" * 70)
print("HIVER SDE - BRAND ISSUE / TEXT DIVERSITY ANALYSIS")
print("=" * 70)

print("\nTop candidate brands:")

for brand in brands_df["author_id"]:
    print(f"- {brand}")


# ============================================================
# 6. PASS 1
# FIND BRAND RESPONSES TO CUSTOMER TWEETS
# ============================================================

# We need to identify which customer tweets are being answered
# by our candidate brands.
#
# A brand response contains:
#
#     author_id = brand
#     inbound = False
#     in_response_to_tweet_id = customer tweet ID
#
# We collect these parent tweet IDs first.
brand_response_links = []


print("\n")
print("=" * 70)
print("PASS 1 - FIND CUSTOMER / BRAND RESPONSE LINKS")
print("=" * 70)


for chunk_number, chunk in enumerate(
    pd.read_csv(
        DATA_PATH,

        # We only load the columns required for this stage.
        usecols=[
            "tweet_id",
            "author_id",
            "inbound",
            "in_response_to_tweet_id",
        ],

        # Process the file in chunks.
        chunksize=CHUNK_SIZE,

        # Prevent pandas from making unwanted dtype guesses.
        low_memory=False,
    ),

    # Start chunk numbering at 1 for easier reading.
    start=1,
):

    print(
        f"Processing chunk {chunk_number}..."
    )


    # Keep only tweets written by our candidate brands.
    brand_rows = chunk[
        chunk["author_id"]
        .astype(str)
        .isin(candidate_brands)
    ].copy()


    # We only want outbound/support messages.
    brand_rows = brand_rows[
        brand_rows["inbound"] == False
    ]


    # A response must have a parent tweet ID.
    brand_rows = brand_rows[
        brand_rows["in_response_to_tweet_id"].notna()
    ]


    # If this chunk contains no matching rows,
    # move to the next chunk.
    if brand_rows.empty:
        continue


    # Convert the parent tweet ID to numeric.
    #
    # This makes it compatible with the tweet_id column
    # used when we retrieve the customer tweet later.
    brand_rows["parent_tweet_id"] = pd.to_numeric(
        brand_rows["in_response_to_tweet_id"],
        errors="coerce"
    )


    # Remove rows where the conversion failed.
    brand_rows = brand_rows[
        brand_rows["parent_tweet_id"].notna()
    ]


    if brand_rows.empty:
        continue


    # Convert the ID to integer.
    brand_rows["parent_tweet_id"] = (
        brand_rows["parent_tweet_id"]
        .astype("int64")
    )


    # Keep only the information needed for the next pass.
    brand_response_links.append(
        brand_rows[
            [
                "author_id",
                "parent_tweet_id",
            ]
        ]
    )


# Make sure we actually found something.
if not brand_response_links:
    raise RuntimeError(
        "No brand/customer response links were found."
    )


# Combine all chunks into one DataFrame.
brand_links = pd.concat(
    brand_response_links,
    ignore_index=True
)


# Extract all customer tweet IDs that need to be retrieved.
parent_ids = set(
    brand_links["parent_tweet_id"]
)


print(
    f"\nCustomer parent tweet IDs to retrieve: "
    f"{len(parent_ids):,}"
)


# ============================================================
# 7. PASS 2
# RETRIEVE CUSTOMER TWEETS
# ============================================================

customer_rows = []


print("\n")
print("=" * 70)
print("PASS 2 - RETRIEVE CUSTOMER MESSAGES")
print("=" * 70)


for chunk_number, chunk in enumerate(
    pd.read_csv(
        DATA_PATH,

        # Only load columns needed for customer messages.
        usecols=[
            "tweet_id",
            "author_id",
            "inbound",
            "created_at",
            "text",
        ],

        chunksize=CHUNK_SIZE,
        low_memory=False,
    ),

    start=1,
):

    print(
        f"Processing chunk {chunk_number}..."
    )


    # Find the tweets referenced by brand responses.
    matching = chunk[
        chunk["tweet_id"].isin(parent_ids)
    ].copy()


    # Nothing to do for this chunk if there are no matches.
    if matching.empty:
        continue


    # Keep only inbound/customer tweets.
    matching = matching[
        matching["inbound"] == True
    ]


    if matching.empty:
        continue


    customer_rows.append(
        matching
    )


# Make sure customer tweets were found.
if not customer_rows:
    raise RuntimeError(
        "No customer tweets were found for the candidate brands."
    )


# Combine all retrieved customer rows.
customer_df = pd.concat(
    customer_rows,
    ignore_index=True
)


print(
    f"\nCustomer tweets retrieved: "
    f"{len(customer_df):,}"
)


# ============================================================
# 8. RENAME CUSTOMER COLUMNS
# ============================================================

# Rename columns to make their purpose explicit after joining.
customer_df = customer_df.rename(
    columns={
        "tweet_id": "parent_tweet_id",
        "author_id": "customer_author_id",
        "created_at": "customer_created_at",
        "text": "customer_text",
    }
)


# ============================================================
# 9. JOIN CUSTOMER MESSAGES TO THEIR BRAND
# ============================================================

# Connect each customer tweet to the brand response that
# referenced it.
customer_brand_df = brand_links.merge(
    customer_df,
    on="parent_tweet_id",
    how="inner"
)


# Remove messages with missing text.
customer_brand_df = customer_brand_df[
    customer_brand_df["customer_text"].notna()
].copy()


# Convert message text to string and remove surrounding spaces.
customer_brand_df["customer_text"] = (
    customer_brand_df["customer_text"]
    .astype(str)
    .str.strip()
)


# ============================================================
# 10. BASIC TEXT CLEANING
# ============================================================

def clean_text(text):
    """
    Perform very light cleaning on customer messages.

    We are NOT doing aggressive preprocessing because this
    is exploratory analysis. We want to preserve the actual
    customer language as much as possible.
    """

    # Convert to string.
    text = str(text)


    # Remove URLs because they generally contribute little
    # to identifying the support issue.
    text = re.sub(
        r"https?://\S+",
        " ",
        text
    )


    # Replace multiple whitespace characters with one space.
    text = re.sub(
        r"\s+",
        " ",
        text
    )


    # Remove leading/trailing spaces.
    return text.strip()


# Apply our cleaning function.
customer_brand_df["clean_text"] = (
    customer_brand_df["customer_text"]
    .apply(clean_text)
)


# ============================================================
# 11. CALCULATE TEXT / DIVERSITY METRICS
# ============================================================

results = []


for brand, group in customer_brand_df.groupby(
    "author_id"
):

    # Keep a maximum number of examples per brand so that
    # one extremely large brand does not dominate this
    # exploratory analysis.
    group = group.head(
        MAX_MESSAGES_PER_BRAND
    )


    # Extract the cleaned customer messages.
    messages = group["clean_text"]


    # Remove extremely short messages.
    #
    # Very short messages such as "ok", "yes", or "help"
    # provide little information for this particular
    # diversity analysis.
    usable_messages = messages[
        messages.str.len() >= 10
    ]


    # --------------------------------------------------------
    # Build a simple vocabulary.
    # --------------------------------------------------------

    words = []


    for message in usable_messages:

        # Extract alphabetic words of at least 3 characters.
        tokens = re.findall(
            r"\b[a-zA-Z]{3,}\b",
            message.lower()
        )

        words.extend(
            tokens
        )


    # Count distinct vocabulary terms.
    unique_words = len(
        set(words)
    )


    # Count all extracted words.
    total_words = len(
        words
    )


    # Calculate average customer-message length.
    if len(usable_messages) > 0:

        average_length = (
            usable_messages
            .str.len()
            .mean()
        )

    else:

        average_length = 0


    # Number of unique customer messages.
    unique_messages = (
        usable_messages
        .nunique()
    )


    # Store the metrics for this brand.
    results.append(
        {
            "brand":
                brand,

            "sample_customer_messages":
                len(group),

            "usable_customer_messages":
                len(usable_messages),

            "unique_customer_messages":
                unique_messages,

            "unique_word_vocabulary":
                unique_words,

            "total_words":
                total_words,

            "avg_message_length":
                round(
                    average_length,
                    2
                ),
        }
    )


# ============================================================
# 12. CREATE RESULTS TABLE
# ============================================================

issue_df = pd.DataFrame(
    results
)


# Sort by vocabulary size as one exploratory indicator
# of textual diversity.
#
# IMPORTANT:
# This is NOT a final ranking of brands.
issue_df = issue_df.sort_values(
    "unique_word_vocabulary",
    ascending=False
).reset_index(
    drop=True
)


# ============================================================
# 13. DISPLAY RESULTS
# ============================================================

print("\n")
print("=" * 70)
print("ISSUE / TEXT DIVERSITY PROXY")
print("=" * 70)

print(
    issue_df.to_string(
        index=False
    )
)


# ============================================================
# 14. SAVE RESULTS
# ============================================================

issue_df.to_csv(
    OUTPUT_PATH,
    index=False
)


print("\n")
print("=" * 70)
print("ANALYSIS COMPLETE")
print("=" * 70)

print(
    f"\nSaved results to:\n"
    f"{OUTPUT_PATH}"
)

print(
    f"\nOutput exists: "
    f"{OUTPUT_PATH.exists()}"
)