"""
Escalation Failure Analysis
---------------------------

Purpose:
    Inspect the HUMAN cases that the current rule-based escalation
    system incorrectly classified as AUTO-HANDLE.

Why:
    False negatives are the most important errors for escalation.
    They show which escalation signals our current rules are missing.

Output:
    - All false-negative examples.
    - The most common terms/phrases in those examples.
    - A CSV file for manual inspection.
"""

# ============================================================
# IMPORTS
# ============================================================

from pathlib import Path
from collections import Counter
import re

import pandas as pd


# ============================================================
# PROJECT PATH
# ============================================================

# Locate the project root automatically.
PROJECT_ROOT = Path(__file__).resolve().parents[1]


# ============================================================
# INPUT / OUTPUT
# ============================================================

# Predictions generated by script 18.
INPUT_FILE = (
    PROJECT_ROOT
    / "results"
    / "rule_escalation_predictions.csv"
)

# Save false negatives separately.
OUTPUT_FILE = (
    PROJECT_ROOT
    / "results"
    / "escalation_false_negatives.csv"
)


# ============================================================
# LOAD DATA
# ============================================================

print("=" * 70)
print("ESCALATION FALSE-NEGATIVE ANALYSIS")
print("=" * 70)

if not INPUT_FILE.exists():

    raise FileNotFoundError(
        f"Prediction file not found:\n{INPUT_FILE}"
    )


df = pd.read_csv(
    INPUT_FILE
)


# ============================================================
# NORMALIZE BOOLEAN COLUMNS
# ============================================================

# Convert true escalation labels into boolean values.
df["true_escalation"] = (
    df["true_escalation"]
    .astype(str)
    .str.strip()
    .str.lower()
    .map(
        {
            "true": True,
            "false": False,
        }
    )
)


# Convert predictions into boolean values.
df["predicted_escalation"] = (
    df["predicted_escalation"]
    .astype(str)
    .str.strip()
    .str.lower()
    .map(
        {
            "true": True,
            "false": False,
        }
    )
)


# ============================================================
# FIND FALSE NEGATIVES
# ============================================================

# False negative means:
#
#     Actual = HUMAN
#     Predicted = AUTO-HANDLE
#
# These are the most important errors for escalation.
false_negatives = df[
    (df["true_escalation"] == True)
    &
    (df["predicted_escalation"] == False)
].copy()


# Save the false negatives.
false_negatives.to_csv(
    OUTPUT_FILE,
    index=False,
)


print(
    f"\nFalse negatives: "
    f"{len(false_negatives)}"
)


# ============================================================
# DISPLAY FALSE NEGATIVES
# ============================================================

print("\n")
print("=" * 70)
print("FALSE-NEGATIVE EXAMPLES")
print("=" * 70)


for index, row in false_negatives.iterrows():

    print("\n")
    print("-" * 70)

    print(
        f"Example {index + 1}"
    )

    print("-" * 70)

    print(
        "\nCustomer message:"
    )

    print(
        row["customer_message"]
    )

    print(
        "\nCurrent rule decision:"
    )

    print(
        row["decision"]
    )

    print(
        "\nCurrent reason:"
    )

    print(
        row["reason"]
    )


# ============================================================
# SIMPLE WORD ANALYSIS
# ============================================================

# Combine all false-negative messages into one string.
all_text = " ".join(
    false_negatives[
        "customer_message"
    ]
    .astype(str)
    .tolist()
).lower()


# Extract alphabetic words with at least 4 characters.
words = re.findall(
    r"\b[a-zA-Z]{4,}\b",
    all_text,
)


# Common English stop words that don't help explain escalation.
stop_words = {
    "this",
    "that",
    "with",
    "have",
    "from",
    "your",
    "they",
    "what",
    "when",
    "were",
    "been",
    "just",
    "will",
    "would",
    "could",
    "about",
    "there",
    "their",
    "them",
    "then",
    "than",
    "into",
    "because",
    "very",
    "only",
    "still",
    "also",
    "after",
    "please",
    "amazon",
}


# Remove stop words.
filtered_words = [
    word
    for word in words
    if word not in stop_words
]


# Count frequent terms.
word_counts = Counter(
    filtered_words
)


# ============================================================
# PRINT FREQUENT TERMS
# ============================================================

print("\n")
print("=" * 70)
print("COMMON TERMS IN MISSED HUMAN CASES")
print("=" * 70)


for word, count in word_counts.most_common(30):

    print(
        f"{word:25s} {count}"
    )


# ============================================================
# SAVE FINISH
# ============================================================

print("\n")
print("=" * 70)
print("ANALYSIS COMPLETE")
print("=" * 70)

print(
    "False-negative file:"
)

print(
    OUTPUT_FILE
)